### PR TITLE
Update poetry.lock and fix the issue if the model id is invalid in the pickle file

### PR DESCRIPTION
**Pull request by BishoyHanyRaafat**

### CODE REVIEW

**Comment by BishoyHanyRaafat** [comment]
@mark-at-pieces

**Comment by BishoyHanyRaafat** [comment]
I think we should ignore the poetry.lock (add it to the gitignore)
and we add the the command poetry lock in the release.yml

**Review by mark-at-pieces — APPROVED** [review]
LGTM

**Review by mark-at-pieces — CHANGES_REQUESTED** [review]
Lets adjust the name of the bool to be more readable, something like invalid_model

**Comment by BishoyHanyRaafat** [comment]
mark that bool used to check whether we create a pickle(pkl) file (the models.pkl which I store the currently using model) or not
we won't create a pickle file if 
1. `models_file.is_file()` means if the models.pkl is a file (exists)
2. if the file exists but the uuid of the model is invalid 
```python
 try: # Checks if the current model is valid
                get_current_model_name()
                create_pickle = False
except:
                pass
```
this right here means if you did not catch any errors while getting the name of the mode l(which uses the uuid that stored in the pkl file) don't create a pickle file

**Comment by mark-at-pieces** [comment]
> mark that bool used to check whether we create a pickle(pkl) file (the models.pkl which I store the currently using model) or not we won't create a pickle file if
> 
> 1. `models_file.is_file()` means if the models.pkl is a file (exists)
> 2. if the file exists but the uuid of the model is invalid
> 
> ```python
>  try: # Checks if the current model is valid
>       get_current_model_name()
>       create_pickle = False
> except:
>       pass
> ```
> 
> this right here means if you did not catch any errors while getting the name of the model (which uses the uuid that stored in the pkl file) set the create_pickle to false (don't create a pickle file) @mark-at-pieces

Thanks for the explanation here this is really useful! Lets still rename this boolean to be a bit more readable.

**Review by mark-at-pieces — APPROVED** [review]
LGTM

**Pull request merged**
