### PR TITLE
Implement SelectCommand with interactive menu for assets, apps, and models #133

### PR DESCRIPTION
**Pull request by sambhavnoobcoder**
## Description
This PR introduces a major refactor, renaming ListCommand to SelectCommand and implementing an interactive selection menu for assets, apps, and models. This change enhances user interaction and provides a more intuitive interface for item selection.

## Changes
1. Renamed ListCommand to SelectCommand
   - Better reflects the class's primary function of selecting items

2. Introduced PiecesSelectMenu class
   - Handles interactive menu selection using prompt_toolkit

3. Refactored command methods:
   - list_command → select_command
   - list_assets → select_assets
   - list_apps → select_apps
   - list_models → select_models

## Motivation
The transition from listing to selecting items necessitated a rename of the main class. This change, along with the new interactive selection mechanism, provides a more intuitive and user-friendly interface. It allows for immediate action on selected items, enhancing the overall functionality and user experience of the tool.

## How to Test
To test the code code you can run the following commands :
1. Activate python console by running command : `python`
2. Next, run the following code to see the outputs : 
`from list_command import SelectCommand`
`SelectCommand.select_command(type="assets", max_assets=5)`

running the following code should help you see your selection menu . replace the type parameters with "apps" or "models" according to your need and requirement .

### CODE REVIEW

**Comment by Bishoy-at-pieces** [comment]
Great job 
Just want to highlight that the name of the function does no affect the command name but that's true an amazing work gonna change some small stuff but true amazing !!

**Comment by sambhavnoobcoder** [comment]
Thank you !

**Comment by Bishoy-at-pieces** [comment]
Can you return the methods names as it is? 
Since in the app.py we are referencing the methods by these names

**Comment by Bishoy-at-pieces** [comment]
And also we don't select menus in the list apps

**Comment by sambhavnoobcoder** [comment]
okay , small changes coming right up . reverting the methods to their _list versions and the app to the previous method

**Comment by Bishoy-at-pieces** [comment]
great seems working just some stuff I would like to change:
1. When you select an asset in the list assets it should execute the AssetsCommands.open_asset
2. similarity the list_models should also do the same and call the change_model function
3. We should leave the on_enter_callback, which is a function to execute. This will be much better than getting the latest selected item and doing whatever with that index. That will be helpful for scalability terms as you will send the callback no need to execute extra stuff related to geting the index (let me know if you need help in that point) ref:https://bishoyatpieces.pieces.cloud/?p=c787439ee9

**Comment by sambhavnoobcoder** [comment]
addressed all three issues , please have a look .

**Comment by Bishoy-at-pieces** [comment]
Seems good gonna do some polishes my self and merge it thank you

**Comment by sambhavnoobcoder** [comment]
okay ,thanks .

**Review by Bishoy-at-pieces — APPROVED** [review]
LGTM thanks @sambhavnoobcoder

**Comment by Bishoy-at-pieces** [comment]
@sambhavnoobcoder just want to make sure that you add these changes to the CHANGELOG.md

**Comment by sambhavnoobcoder** [comment]
okay , I'll do that .

**Review by mark-at-pieces — APPROVED** [review]
LGTM, might want to verify the changes w/ our tests or write some new ones, but looking solid!

**Pull request merged**
