### PR TITLE
fixes piece list command help text

### PR DESCRIPTION
**Pull request by abhinayy0**

### CODE REVIEW

**Comment by abhinayy0** [comment]
fixes #43

**Review by hal-8999-alpha — COMMENTED** [review]
Thank you, can you also update the GUI for this issue

**Comment by mark-at-pieces** [comment]
@abhinayy0 this is the file Jayson is referring to https://github.com/pieces-app/cli-agent/blob/main/src/pieces/gui.py

Thank you for the contribution!

**Comment by mark-at-pieces** [comment]
hey @abhinayy0 looks like there are some conflicts, please let me know if you want some help here

**Comment by abhinayy0** [comment]
@mark-at-pieces Issue got resolved in other PR an can be marked as closed: https://github.com/pieces-app/cli-agent/pull/71

**Pull request closed without merging**
